### ISSUE TITLE
Bone layers needs to be updated for Blender 4.x

### ISSUE THREAD

**Issue by jentron** [jentron/Blender-PT2#44]

**Comment by jentron** [comment]
https://developer.blender.org/docs/release_notes/4.0/upgrading/bone_collections/

**Comment by jentron** [comment]
I was wrong about the source of the problem because proxy_picker.py is throwing an error in the same place:

```
Error in bpy.app.handlers.depsgraph_update_pre[0]:
Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\proxy_picker.py", line 190, in proxy_picker
    if bone_layer_active(b) == False:
       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\proxy_picker.py", line 22, in bone_layer_active
    if b.layers[i] == True and ob.data.layers[i] == True:
       ^^^^^^^^
AttributeError: 'Bone' object has no attribute 'layers'
=========================================================
```

Not my monkey not my circus
