### ISSUE TITLE
Still have errors with 2.82a

### ISSUE THREAD

**Issue by dlorre** [jentron/Blender-PT2#9]
Hey, I have tried installing from zip on 2.82a, here are the errors I get:

Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "D:\Utilisateurs\Dominique\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Blender-PT2-master\__init__.py", line 49, in <module>
    from . import PDB1
  File "D:\Utilisateurs\Dominique\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Blender-PT2-master\PDB1.py", line 29, in <module>
    import os, glob, inspect, sys, PT2
ModuleNotFoundError: No module named 'PT2'

Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "D:\Utilisateurs\Dominique\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Blender-PT2-master\__init__.py", line 49, in <module>
    from . import PDB1
  File "D:\Utilisateurs\Dominique\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Blender-PT2-master\PDB1.py", line 29, in <module>
    import os, glob, inspect, sys, PT2
ModuleNotFoundError: No module named 'PT2'

**Comment by jentron** [comment]
It is important that the folder containing the \_\_init\_\_.py file be named PT2, so please try renaming "D:\Utilisateurs\Dominique\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\Blender-PT2-master\" as "D:\Utilisateurs\Dominique\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\PT2\"

**Comment by dlorre** [comment]
That works, however you should rename the directory so that it can be installed the normal way, i.e. by Preferences > AddOns > Install. I have tried importing a character from DAZ and I see the bones, the orientation is horizontal. For a prop, I get this error:

Traceback (most recent call last):
  File "D:\Utilisateurs\Dominique\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\PT2\PPI12.py", line 804, in execute
    mesh.uv_layers.active.data[loop_idx].uv = UVvertices[vert_idx]
IndexError: list index out of range

location: <unknown location>:-1

I'll keep looking but my main concern is to export rigged meshes from Blender to Poser so that I can animate them.

**Comment by jentron** [comment]
I just pushed a patch that should fix this index out of range error, and fix the UV imports on PPI and PCI
